version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm i -g eslint
      - npm i -g typescript aws-cdk

  pre_build:
    commands:
      # provisions a CloudFormation stack
      - cdk bootstrap
      # confirm CloudFormation template is generated successfully
      - cdk synth
      # create resources
      - cdk deploy

  build:
    commands:
      - echo "Building React project..."
      - npm run build
  
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync build/ s3://backend-icon-bucket-test/